yolo_model:

  config_file:
    name: yolov3-tiny-aras.cfg
  weight_file:
    name: yolov3-tiny-aras_final.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - left
      - right
      - curve_left
      - curve_right
      - construction
      - slippery
      - stop
      - parking
      - parking_spot
      - human
      - unknown     
